### ISSUE TITLE
aws-sdk-resources errors

### ISSUE THREAD

**Issue by Dariusch** [aws/aws-sdk-ruby#1239]
Hey guys,
we are having some issues for a while.
We get errors regarding the communication with Aws::S3::Resource

here are the stack traces:
1:
```
/home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:255:in `block in builder_sources': undefined method `_builder_source' for #<Aws::Resources::Definition:0x0000000b410b80> (NoMethodError)
Did you mean?  builder_sources
               data_builder_source
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:254:in `map'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:254:in `builder_sources'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:249:in `define_builder'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:149:in `has_many'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:221:in `block in define_has_many'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:220:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:220:in `define_has_many'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:27:in `block in apply'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:48:in `block in each_resource_class'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:312:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:312:in `each_definition'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:47:in `each_resource_class'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:21:in `apply'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources.rb:32:in `block in <module:Aws>'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:434:in `block in add_service'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:433:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:433:in `add_service'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/s3.rb:1:in `<top (required)>'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
```
2:
```
/home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:35:in `[]': unknown shape nil (ArgumentError)
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:52:in `shape_ref'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:93:in `block in apply_shape_refs'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:91:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:91:in `apply_shape_refs'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:82:in `block in build_shapes'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:79:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:79:in `build_shapes'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:28:in `initialize'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/builder.rb:66:in `new'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/builder.rb:66:in `build_shape_map'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/builder.rb:39:in `build'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/builder.rb:12:in `build'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/client.rb:42:in `define'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:444:in `block in <module:Aws>'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:434:in `block in add_service'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:433:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:433:in `add_service'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/s3.rb:1:in `<top (required)>'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
...
```
3:
```
/home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:183:in `define_request': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:128:in `build_basic_action'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:122:in `build_operation'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:106:in `block in define_actions'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:105:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:105:in `define_actions'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:23:in `block in apply'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:48:in `block in each_resource_class'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:312:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:312:in `each_definition'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:47:in `each_resource_class'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources/definition.rb:21:in `apply'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-resources-2.3.17/lib/aws-sdk-resources.rb:32:in `block in <module:Aws>'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:434:in `block in add_service'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:433:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:433:in `add_service'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/s3.rb:1:in `<top (required)>'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
```
4:
```
/home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:75:in `block in build_shapes': undefined method `new' for nil:NilClass (NoMethodError)
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:74:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:74:in `build_shapes'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/shape_map.rb:28:in `initialize'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/builder.rb:66:in `new'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/builder.rb:66:in `build_shape_map'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/builder.rb:39:in `build'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/api/builder.rb:12:in `build'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/client.rb:42:in `define'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:444:in `block in <module:Aws>'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:434:in `block in add_service'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:433:in `each'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core.rb:433:in `add_service'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/aws-sdk-core-2.3.17/lib/aws-sdk-core/s3.rb:1:in `<top (required)>'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/rails-deploy/buddy/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
```

our Call:
```ruby
Aws.config.update({
  region: AMAZON_S3_CONFIG[:aws_server_region],
  credentials: Aws::Credentials.new(AMAZON_S3_CONFIG[:aws_access_key_id], AMAZON_S3_CONFIG[:aws_secret_access_key]) })
Aws.use_bundled_cert!
@bucket = Aws::S3::Resource.new.bucket(AMAZON_S3_CONFIG[:bucket])
binary = Base64.decode64(Base64.decode64(some_file[:file_data]))
@bucket.object(some_file[:file_name]).put(body: binary)
```

Any ideas why this keeps happening?
Did I miss some something in the changelog?
Thank you guys

**Comment by awood45** [comment]
It may be helpful to see your JMESPath version and Ruby version, given an ongoing issue we've had there. Otherwise, I'll try to replicate your issue.

**Comment by Dariusch** [comment]
JMESPath version is 1.2.4
Ruby Version was 2.3.0

**Comment by trevorrowe** [comment]
As far as I can tell from the stack traces above, this is unrelated to the `jmespath` gem issue. Can you update to the latest version and test again. This should not normally make any difference, but it appears almost as if you have a truncated version of the service resource definitions JSON document. A gem update would update this. If this does not resolve the issue, could you share a gist of your Gemfile.lock so we can see if there is maybe another library that is causing grief?

**Comment by fedot** [comment]
We also have **2** and **4** cases of OP with `2.3.21`.

jmespath - 1.3.0
ruby - 2.3.1 and 2.2.4

**Comment by Dariusch** [comment]
As far as I can tell the issue is resolved.
There are no more errors with the new `jmespath version 1.3.1`

**Comment by fedot** [comment]
This doesn't looks related to `jmespath` (and using `1.3.1` doesn't resolve those issues)

3 out of 4 posted by OP still happen for us.

- Ruby 2.3.1
- aws-sdk-ruby 2.4.0
- jmespath 1.3.1

**Comment by trevorrowe** [comment]
I agree that the issue is unrelated to JMESPath. @fedot Can you provide more context to when the error occurs?
