### ISSUE TITLE
Shared credentials not being loaded from ~/.aws/credentials or ~/.aws/config

### ISSUE THREAD

**Issue by matt9949** [aws/aws-sdk-ruby#1621]
### Issue description

SharedCredentials are not being loaded from ~/.aws/config or ~/.aws/credentials at all. 

As per http://docs.aws.amazon.com/sdkforruby/api/Aws/EC2/Client.html#initialize-instance_method :

:credentials (required, Credentials) — Your AWS credentials. The following locations will be searched in order for credentials:
:access_key_id, :secret_access_key, and :session_token options
ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY']
HOME/.aws/credentials shared credentials file
EC2 instance profile credentials See Plugins::RequestSigner for more details.
Tested with aws-sdk version: aws-sdk-core-2.10.53

When i set AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID as the 'services' creds, the instance is initialised correctly and i can authenticate.

However when using the shared credentials file, it doesn't pick up the creds.

### Gem name ('aws-sdk', 'aws-sdk-resources' or service gems like 'aws-sdk-s3') and its version
aws-sdk:2.10.53

### Version of Ruby, OS environment
OSX 10.12.3, Ruby 2.4.0

### Code snippets / steps to reproduce

~/.aws/credentials

[services]
aws_access_key_id=xyz
aws_secret_access_key=xyz

~/.aws/config

[profile dev]
role_arn = arn:aws:iam::<id>
source_profile = services
mfa_serial = arn:aws:iam::<id>
region = eu-west-1

[profile staging]
role_arn = arn:aws:iam::<id>
source_profile = services
mfa_serial = arn:aws:iam::<id>
region = eu-west-1

Using the SDK:

Without AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID set:

$ bundle exec irb
irb(main):001:0> require 'aws-sdk'
=> true
irb(main):002:0> client = Aws::EC2::Client.new(region: 'eu-west-1')
=> #<Aws::EC2::Client>
irb(main):003:0> client.run_instances(image_id: "ami-8e74b3f7", max_count: "1", min_count: "1")
Aws::Errors::MissingCredentialsError: unable to sign request without credentials set
	from /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.53/lib/aws-sdk-core/plugins/request_signer.rb:104:in `require_credentials'

With AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID set:

bundle exec irb
irb(main):001:0> require 'aws-sdk'
=> true
irb(main):002:0> client = Aws::EC2::Client.new(region: 'eu-west-1')
=> #<Aws::EC2::Client>
irb(main):003:0> client.run_instances(image_id: "ami-8e74b3f7", max_count: "1", min_count: "1")
Aws::EC2::Errors::AuthFailure: Not authorized for images: [ami-8e74b3f7]

(i get an authorization failure but it authenticates)

I want to use profiles set in ~/.aws/config however it seems i cannot. I've tried setting AWS_PROFILE also to no avail.

Anyone come across this issue or have a fix?

Could be linked to https://github.com/aws/aws-sdk-ruby/issues/1504

**Comment by rhyas** [comment]
I looked at the code for this, and it seems as if the documentation is just flat wrong. It implies it supports the config options with role_arn and source_profile, but the actual code for shared_credentials does not actually do anything related to that process. It defaults to only using the credentials file and keys therein. Seems like a pretty major issue if the documentation says it should work, but there's no code/functionality to support it. Also, this issue applies to both V2 and V3, they have essentially the same module code.

**Comment by awood45** [comment]
There is a shortcoming with MFA that you can work around by using `Aws::AssumeRoleCredentials` directly. What value are you setting for `AWS_PROFILE`?

**Comment by awood45** [comment]
Actually, the MFA case may still require client calls directly, it's on a feature request backlog across the SDKs.

**Comment by rhyas** [comment]
So this is basically using the Assume Role functionality in the SDK via configs. http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html. The SDK supports this, but what I have come to understand, and this is where the documentation is wrong, it only works if you *don't* feed include a Credentials object in the config, rather only feed it profile arg, and let the client object discover credentials. None of the Credential objects correctly does the Assume Role from configs. The documentation actually implies that you *must* feed a credentials object, but it's wrong. You exclude credentials, and it will do the searching.

**Comment by awood45** [comment]
It should actually give preference to the presence of the `source_profile` config value. For example, we have [unit tests](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-core/spec/aws/credential_resolution_chain_spec.rb#L50) which specifically validate this.

It may help if you provide a redacted version of your shared configuration setup, and how you're constructing a client.

**Comment by rhyas** [comment]
I discovered this trying to use the kitchen-ec2 package with assumed roles. The code in question is here: https://github.com/test-kitchen/kitchen-ec2/blob/master/lib/kitchen/driver/aws/client.rb and to make things work, I replaced line 50 to be `:profile = profile_name`

**Comment by awood45** [comment]
Interesting - I'm looking at the code now to see if there is an obvious fix, but it looks like this is hand-rolling its own credential provider chain. So what the SDK does or does not do with regards to role assumption wouldn't apply.

**Comment by awood45** [comment]
It also looks like the hand-rolled implementation here is using private APIs, and it's totally understandable that it would skip the SDK's later-updated logic around Shared Config completely. We did not implement assume role credential support in the SharedCredentials class.

**Comment by awood45** [comment]
@matt9949 are you also having this problem via `kitchen-ec2`, or directly? Trying to see if these are related issues.

**Comment by rhyas** [comment]
You can say it's "hand rolled", but it's following the documentation, or attempting to. The documentation specifically states that you have to provide credentials, and there are only 4 classes, none of which allow you to use the config option of assumed role. I suspect that this ticket, even if it's not using kitchen-ec2, was trying to follow the documentation and running into the same problem. So the issue is not specifically a bug in the SDK, it's a bug in the documentation. (:

**Comment by awood45** [comment]
That's fair, and the dev guide you linked should have a feedback form. I'm going to tag this as a Documentation issue for the moment so we can look at more clarity in our own docs.

**Comment by awood45** [comment]
It does look like `kitchen-ec2` may have hand-rolled their credential chain to have AssumeRole support in a provider chain, before we implemented it (V2 did not ship with AssumeRole support in the credential provider chain, it was added later).

**Comment by matt9949** [comment]
Hey guys, thanks for looking at this. @awood45 not using kitchen-ec2, i'm using a library called [ami_spec](https://github.com/envato/ami-spec) to spin up a temporary EC2 instance with an AMI I have built/made changes to for acceptance testing. I believe the library uses the ruby aws-sdk for spinning up EC2 instances.

**Comment by cjyclaire** [comment]
Soft checking, does the issue still happening for you?

Since this is surfaced by `ami_spec`, could you try open an issue with them first about this issue? 
I did a quick check in the `ami_spec`, I didn't see any custom wrapper for assume role/ MFA. This has already been a feature tracked in our feature backlog, can I take your request as a +1 for that?

If you still seeing any issues reproducible with our SDK, it would be great if you can share some code snippets for us to reproduce.

**Comment by cjyclaire** [comment]
Closing due to ages, have added +1 for the feature request in your backlog, feel free to reopen with further info/questions : )
