### ISSUE TITLE
Where are Client options described in V3 documentation?

### ISSUE THREAD

**Issue by lwoggardner** [aws/aws-sdk-ruby#1649]
### Issue description
In V2 docs the available options for a client are enumerated on the Client initialize() method documentation.

http://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CloudFormation/Client.html#initialize-instance_method
 
In V3 I cannot find the client options documented anywhere.

http://docs.aws.amazon.com/sdkforruby/api/Aws/CloudFormation/Client.html#initialize-instance_method

**Comment by cjyclaire** [comment]
Hmm they are actually [here](https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/client.rb#L79) at client docs, might be a YARD rendering problem, will fix this

**Comment by lwoggardner** [comment]
Is it because it is calling it "options" but the method is defined as "*args" so there is no matching parameter called "options" ?

 # @option options [required, Aws::CredentialProvider] :credentials

def initialize(*args)

**Comment by awood45** [comment]
This has been resolved.

**Comment by lwoggardner** [comment]
I'm still not seeing these docs on the Client initialize methods.

**Comment by kgalli** [comment]
Will this be tackled anytime soon. I can probably find it in the code as already mentioned in this thread. But that destroys the whole idea of easy to read documentation ...

**Comment by srchase** [comment]
A fix for this has been merged.  The documentation will get updated with the next release.
